/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Bid } from "./Bid";
import { BidCountArgs } from "./BidCountArgs";
import { BidFindManyArgs } from "./BidFindManyArgs";
import { BidFindUniqueArgs } from "./BidFindUniqueArgs";
import { CreateBidArgs } from "./CreateBidArgs";
import { UpdateBidArgs } from "./UpdateBidArgs";
import { DeleteBidArgs } from "./DeleteBidArgs";
import { Job } from "../../job/base/Job";
import { UserFindUniqueArgs } from "../../user/base/UserFindUniqueArgs";
import { BidService } from "../bid.service";
@graphql.Resolver(() => Bid)
export class BidResolverBase {
  constructor(protected readonly service: BidService) {}

  async _bidsMeta(
    @graphql.Args() args: BidCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Bid])
  async bids(@graphql.Args() args: BidFindManyArgs): Promise<Bid[]> {
    return this.service.bids(args);
  }

  @graphql.Query(() => Bid, { nullable: true })
  async bid(@graphql.Args() args: BidFindUniqueArgs): Promise<Bid | null> {
    const result = await this.service.bid(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Bid)
  async createBid(@graphql.Args() args: CreateBidArgs): Promise<Bid> {
    return await this.service.createBid({
      ...args,
      data: {
        ...args.data,

        job: args.data.job
          ? {
              connect: args.data.job,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Bid)
  async updateBid(@graphql.Args() args: UpdateBidArgs): Promise<Bid | null> {
    try {
      return await this.service.updateBid({
        ...args,
        data: {
          ...args.data,

          job: args.data.job
            ? {
                connect: args.data.job,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Bid)
  async deleteBid(@graphql.Args() args: DeleteBidArgs): Promise<Bid | null> {
    try {
      return await this.service.deleteBid(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Job, {
    nullable: true,
    name: "job",
  })
  async getJob(@graphql.Parent() parent: Bid): Promise<Job | null> {
    const result = await this.service.getJob(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => String)
  async AdminManageBid(
    @graphql.Args()
    args: UserFindUniqueArgs
  ): Promise<string> {
    return this.service.AdminManageBid(args);
  }

  @graphql.Mutation(() => String)
  async EditorManageBid(
    @graphql.Args()
    args: UserFindUniqueArgs
  ): Promise<string> {
    return this.service.EditorManageBid(args);
  }

  @graphql.Mutation(() => String)
  async UserManageBid(
    @graphql.Args()
    args: UserFindUniqueArgs
  ): Promise<string> {
    return this.service.UserManageBid(args);
  }
}
